framework:
  - terraform

skip-check:
  - CKV_AWS_338
  - CKV_AWS_66
  - CKV_AWS_158
  - CKV_AWS_65
  - CKV_AWS_24
  - CKV_AWS_23
  - CKV_AWS_277
  - CKV_AWS_382
  - CKV_AWS_25
  - CKV_AWS_260
  - CKV_AWS_2
  - CKV_AWS_115
  - CKV_AWS_116
  - CKV_AWS_50
  - CKV_AWS_272
  - CKV_AWS_117
  - CKV_AWS_23
  - CKV_AWS_382
  - CKV_AWS_260
  - CKV_AWS_91
  - CKV_AWS_150
  - CKV_AWS_131
  - CKV_AWS_28
  - CKV_AWS_119
  - CKV_AWS_23
  - CKV_AWS_382
  - CKV_AWS_26
  - CKV_AWS_27
  - CKV2_AWS_65
  - CKV2_AWS_20
  - CKV_AWS_103
  - CKV_AWS_21
  - CKV2_AWS_61
  - CKV_AWS_145
  - CKV_AWS_144
  - CKV_AWS_378
  - CKV2_AWS_28
  - CKV_AWS_18
  - CKV_AWS_173
