name: Infrastructure and API tests for DEV environment

on:
  workflow_call:

env:
  S3_BUCKET_ARTIFACTS: "set-cicd-artifacts"
  INF_TEST_REPORTS: "inf-test-results"
  API_TEST_REPORTS: "api-test-results"

jobs:
  test-env-setup:
    runs-on: codebuild-ImageRecApp-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables
        run: echo "PYTHONPATH=." >> $GITHUB_ENV

      - name: Install Python 3
        run: |
          sudo apt -y update
          sudo apt install -y python3 python3-virtualenv

      - name: Setup virtual environment
        run: |
          python3 -m venv venv
          echo "VIRTUAL_ENV=$(pwd)/venv" >> $GITHUB_ENV
          echo "$(pwd)/venv/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          . venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install -r tests/requirements.txt

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: venv
          key: python-deps-${{ runner.os }}-${{ hashFiles('tests/requirements.txt') }}

  test-inf-dev:
    runs-on: codebuild-ImageRecApp-${{ github.run_id }}-${{ github.run_attempt }}
    needs: test-env-setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore cached dependencies
        uses: actions/cache@v3
        with:
          path: venv
          key: python-deps-${{ runner.os }}-${{ hashFiles('tests/requirements.txt') }}

      - name: Set environment variables
        run: echo "PYTHONPATH=." >> $GITHUB_ENV

      - name: Run infrastructure test
        run: |
          . venv/bin/activate
          venv/bin/python -m pytest -v tests/test_aws_infrastructure_dev.py --html=pytest-report-dev.html --junitxml=pytest-report-dev.xml

      - name: Upload test results to S3
        run: |
          aws s3 cp pytest-report-dev.xml s3://$S3_BUCKET/$INF_TEST_REPORTS/${{ github.run_id }}/pytest-report-dev.xml
          aws s3 cp pytest-report-dev.html s3://$S3_BUCKET/$INF_TEST_REPORTS/${{ github.run_id }}/pytest-report-dev.html

  test-api-dev:
    runs-on: codebuild-ImageRecApp-${{ github.run_id }}-${{ github.run_attempt }}
    needs: test-env-setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore cached dependencies
        uses: actions/cache@v3
        with:
          path: venv
          key: python-deps-${{ runner.os }}-${{ hashFiles('app/requirements.txt') }}

      - name: Set environment variables
        run: echo "PYTHONPATH=." >> $GITHUB_ENV

      - name: Run API tests
        run: |
          . venv/bin/activate
          venv/bin/python -m pytest -v tests/test_api_dev.py --html=pytest-report-dev.html --junitxml=pytest-report-dev.xml

      - name: Upload test results to S3
        run: |
          aws s3 cp pytest-report-dev.xml s3://$S3_BUCKET/$API_TEST_REPORTS/${{ github.run_id }}/pytest-report-dev.xml
          aws s3 cp pytest-report-dev.html s3://$S3_BUCKET/$API_TEST_REPORTS/${{ github.run_id }}/pytest-report-dev.html
