name: Deployment Pipeline Main Branch

on:
  push:
    branches:
      - main

env:
  S3_BUCKET: "set-cicd-artifacts"
  LAMBDA_NAME: "lambda_script_prod"
  ECS_CLUSTER_NAME: "ECSRecAppClusterProd"
  ECS_SERVICE_NAME: "ECSServiceRecAppProd"
  PATH_TO_IMAGEDEF: "imagedefinitions/prod/imagedefinitions.json"

jobs:
  build-and-store:
    name: Build and Store Artifacts
    uses: ./.github/workflows/build_artifacts.yml

  trigger-codepipeline-prod:
    name: Deploy ECR image and Lambda to PROD environment
    needs: [build-and-store]
    runs-on: codebuild-ImageRecApp-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Trigger AWS CodePipeline
        run: aws codepipeline start-pipeline-execution --name deploy-prod
